create table if not exists public.friend_requests (
  id bigint generated by default as identity primary key,
  sender_user_id uuid not null
    constraint friend_requests_sender_profile_fkey
    references public.profiles (user_id)
    on delete cascade,
  receiver_user_id uuid not null
    constraint friend_requests_receiver_profile_fkey
    references public.profiles (user_id)
    on delete cascade,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  responded_at timestamptz,
  constraint friend_requests_status_check check (status in ('pending', 'accepted', 'declined')),
  constraint friend_requests_different_users_check check (sender_user_id <> receiver_user_id)
);

create unique index if not exists friend_requests_pending_pair_unique_idx
on public.friend_requests (
  least(sender_user_id, receiver_user_id),
  greatest(sender_user_id, receiver_user_id)
)
where status = 'pending';

create index if not exists friend_requests_receiver_status_created_idx
on public.friend_requests (receiver_user_id, status, created_at desc);

create index if not exists friend_requests_sender_status_created_idx
on public.friend_requests (sender_user_id, status, created_at desc);

create table if not exists public.friendships (
  user_id uuid not null
    constraint friendships_user_profile_fkey
    references public.profiles (user_id)
    on delete cascade,
  friend_user_id uuid not null
    constraint friendships_friend_profile_fkey
    references public.profiles (user_id)
    on delete cascade,
  created_at timestamptz not null default now(),
  constraint friendships_pkey primary key (user_id, friend_user_id),
  constraint friendships_different_users_check check (user_id <> friend_user_id)
);

create index if not exists friendships_user_created_idx
on public.friendships (user_id, created_at asc);

alter table public.friend_requests enable row level security;
alter table public.friendships enable row level security;

drop policy if exists "Users can view their friend requests" on public.friend_requests;
create policy "Users can view their friend requests"
on public.friend_requests
for select
to authenticated
using (auth.uid() = sender_user_id or auth.uid() = receiver_user_id);

drop policy if exists "Users can view their friendships" on public.friendships;
create policy "Users can view their friendships"
on public.friendships
for select
to authenticated
using (auth.uid() = user_id);

grant select on public.friend_requests to authenticated;
grant select on public.friendships to authenticated;

create or replace function public.send_friend_request(target_user_id uuid)
returns public.friend_requests
language plpgsql
security definer
set search_path = public
as $$
declare
  requester_id uuid := auth.uid();
  existing_request public.friend_requests;
  inserted_request public.friend_requests;
begin
  if requester_id is null then
    raise exception 'You must be signed in to send a friend request.';
  end if;

  if target_user_id is null then
    raise exception 'Choose a user before sending a friend request.';
  end if;

  if requester_id = target_user_id then
    raise exception 'You cannot send yourself a friend request.';
  end if;

  if not exists (
    select 1
    from public.profiles
    where user_id = requester_id
      and username is not null
  ) then
    raise exception 'Choose a username before using friends.';
  end if;

  if not exists (
    select 1
    from public.profiles
    where user_id = target_user_id
      and username is not null
  ) then
    raise exception 'That user is not available for friend requests.';
  end if;

  if exists (
    select 1
    from public.friendships
    where user_id = requester_id
      and friend_user_id = target_user_id
  ) then
    raise exception 'You are already friends with this user.';
  end if;

  select *
  into existing_request
  from public.friend_requests
  where status = 'pending'
    and (
      (sender_user_id = requester_id and receiver_user_id = target_user_id)
      or
      (sender_user_id = target_user_id and receiver_user_id = requester_id)
    )
  order by created_at desc
  limit 1;

  if found then
    if existing_request.sender_user_id = target_user_id then
      raise exception 'This user already sent you a friend request.';
    end if;

    raise exception 'A friend request is already pending.';
  end if;

  insert into public.friend_requests (
    sender_user_id,
    receiver_user_id
  )
  values (
    requester_id,
    target_user_id
  )
  returning *
  into inserted_request;

  return inserted_request;
end;
$$;

create or replace function public.accept_friend_request(friend_request_id bigint)
returns public.friend_requests
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id uuid := auth.uid();
  request_row public.friend_requests;
begin
  if current_user_id is null then
    raise exception 'You must be signed in to accept a friend request.';
  end if;

  select *
  into request_row
  from public.friend_requests
  where id = friend_request_id
  for update;

  if not found then
    raise exception 'That friend request no longer exists.';
  end if;

  if request_row.receiver_user_id <> current_user_id then
    raise exception 'You can only accept requests sent to you.';
  end if;

  if request_row.status <> 'pending' then
    raise exception 'That friend request is no longer pending.';
  end if;

  insert into public.friendships (user_id, friend_user_id)
  values
    (request_row.sender_user_id, request_row.receiver_user_id),
    (request_row.receiver_user_id, request_row.sender_user_id)
  on conflict do nothing;

  update public.friend_requests
  set status = 'accepted',
      responded_at = now()
  where id = friend_request_id
  returning *
  into request_row;

  return request_row;
end;
$$;

create or replace function public.decline_friend_request(friend_request_id bigint)
returns public.friend_requests
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id uuid := auth.uid();
  request_row public.friend_requests;
begin
  if current_user_id is null then
    raise exception 'You must be signed in to decline a friend request.';
  end if;

  select *
  into request_row
  from public.friend_requests
  where id = friend_request_id
  for update;

  if not found then
    raise exception 'That friend request no longer exists.';
  end if;

  if request_row.receiver_user_id <> current_user_id then
    raise exception 'You can only decline requests sent to you.';
  end if;

  if request_row.status <> 'pending' then
    raise exception 'That friend request is no longer pending.';
  end if;

  update public.friend_requests
  set status = 'declined',
      responded_at = now()
  where id = friend_request_id
  returning *
  into request_row;

  return request_row;
end;
$$;

grant execute on function public.send_friend_request(uuid) to authenticated;
grant execute on function public.accept_friend_request(bigint) to authenticated;
grant execute on function public.decline_friend_request(bigint) to authenticated;
